### PR TITLE
Distinguish between HEIF and HEIC

### PR DESCRIPTION
**Pull request by rsuu**
Now, return Avif for .avif and Heic for .heic/heif.

### CODE REVIEW

**Comment by virtualritz** [comment]
This fails CI because of #35.

**Comment by Roughsketch** [comment]
Thanks for the PR, I'll try to review it later when I have time.

My main thought at the moment without reviewing is what is the use case for this change? I don't know if having 2 return values for HEIF and HEIC is helpful.

**Comment by rsuu** [comment]
That because `image_type()` is now always return `Heif` on `.heic` and `.avif`. 

```rust
match ... {
    // before 
    // failed: because HEIF is unsupported by image crate
    ImageType::Heif => image::open( .avif or .heic ),

    // after
    ImageType::Heic => heic::open(),
    ImageType::Avif => image::open(),
}
```

**Comment by Roughsketch** [comment]
Thanks, that makes sense to me.

Initial pass seems probably fine, but I want to take some time to do a code style pass and probably run a fuzzer on it to make sure there aren't any obvious edge cases.

**Comment by virtualritz** [comment]
We use `imagesize` for a file transfer tool with UI.
We want to display the right icon for each file type and we do have different icons for HEIF and HEIC.

I.e. for us this would be cool to have, even though we're not connected to this PR.

**Review by Roughsketch — APPROVED** [review]

**Pull request merged**
