### PR TITLE
Add features flags for each image format

### PR DESCRIPTION
**Pull request by ShadowMitia**
This PR adds features flags as mentioned in #30.

### CODE REVIEW

**Comment by Roughsketch** [comment]
Thank you very much for taking the time to do this! It might be a day or so before I can review it properly, but I'll try to do it sooner rather than later.

**Comment by Roughsketch** [comment]
Not sure the best way to go about larger review changes so I made a PR into your branch: https://github.com/ShadowMitia/imagesize/pull/1

**Review by Roughsketch — APPROVED** [review]
Thanks!

**Comment by ShadowMitia** [comment]
Pleasure!

**Pull request merged**
